#!/usr/bin/env bash

zenity --warning --text "OFF MOUSE" --width=300 

wm=$(wmctrl -m 2>/dev/null | grep "Name" | cut -d " " -f2)
[[ -z $wm ]] && wm="$(xprop -root -notype _NET_WM_NAME | awk 'END{print $3}' | tr -d \")" || wm=$wm
[[ $wm == xfce ]] && wm_name="xfce4" || wm_name="xfce"

DIALOG_RESULT=$(echo -e "Exit $wm_name\nLock\nSuspend Lock\nHibernate\nReboot\nPoweroff" | rofi -dmenu -i -p "SYSTEM" -font "ClearSansMedium 12" -theme-str 'window {width: 25%;height: 30%;}')

if [ "$DIALOG_RESULT" = "Exit $wm_name" ]; then
    [[ $wm == xfce4 ]] && i3-msg 'exit' || xfce4-session-logout --logout
elif [ "$DIALOG_RESULT" = "Lock" ]; then
    exec $HOME/.bin/multilock.sh -l blur
elif [ "$DIALOG_RESULT" = "Suspend Lock" ]; then
    exec $HOME/.bin/multilock.sh -l blur &
    exec systemctl suspend
elif [ "$DIALOG_RESULT" = "Hibernate" ]; then
    exec systemctl hibernate
elif [ "$DIALOG_RESULT" = "Reboot" ]; then
    exec systemctl reboot
elif [ "$DIALOG_RESULT" = "Poweroff" ]; then
    exec systemctl poweroff
fi
