#!/bin/sh

set -e

daemon=${1:?}
state="%{F#965dff}%{F-}"
cmd="$(systemctl status $daemon | grep -i ": active" 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#965dff}%{F-}"

echo "%{F#AEB4C6}warp%{F-} ${state}"
exit 0
